import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { TopNav } from "./_components/topNav";
import { ClerkProvider } from "@clerk/nextjs";
import { IBM_Plex_Sans } from 'next/font/google'

const plex = IBM_Plex_Sans({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-plex-sans',
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={`flex flex-col`}>
      <TopNav /> 
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
